import type { Metadata } from "next";
import { Outfit, Quicksand } from "next/font/google";
import "./globals.css";
import Ticker from "@/components/ticker";

const outfit = Quicksand({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} overflow-y-hidden antialiased`}>
        {/* <div className="w-screen overflow-hidden"> */}
          <Ticker />
        {/* </div> */}
        {/* <div className="w-screen overflow-hidden overflow-y-auto"> */}
          {children}
        {/* </div> */}
      </body>
    </html>
  );
}
