import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Ticker from "@/components/ticker";

const outfit = Quicksand({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Stock Ticker App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} overflow-x-hidden antialiased flex flex-col`}>
        <Ticker />
        {children}
      </body>
    </html>
  );
}
